application: osxkobo
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html

- url: /(.*)
  static_files: site/\1
  upload: site/(.*)

- url: .*
  script: main.py

  
- url: /.*
  script: not_found.py